In [1]:
print("_"*150)
print("                                                             * PROJECT 1 *                                                                 ")
print("")
print("                                                  Data Cleaning in Sales Dataset                                                    ")
print("_"*150)

______________________________________________________________________________________________________________________________________________________
                                                             * PROJECT 1 *

                                                  Data Cleaning in Sales Dataset
______________________________________________________________________________________________________________________________________________________

In [2]:
# Import libraries
import pandas as pd
import numpy as np

In [3]:
#Loading our dataset using pandas library
vssd = pd.read_csv(r"F:\sumit\Vrinda Store Sales Dataset\Uncleaned Vrinda Store Sales Data.csv")               #vssd = Vrinda store sales dataset
print(vssd)

       index             Order ID  Cust ID Gender  Age        Date     Status  \
0          1  171-1029312-3038738  1029312  Women   44  04-12-2022  Delivered
1          2  405-2183842-2225946  2183842  Women   29  04-12-2022  Delivered
2          3  171-1641533-8921966  1641533  Women   67  04-12-2022  Delivered
3          4  404-7490807-6300351  7490807  Women   20  04-12-2022  Delivered
4          5  403-9293516-4577154  9293516  Women   62  04-12-2022  Delivered
...      ...                  ...      ...    ...  ...         ...        ...
31042  31043  405-4724097-1016369  4724097      M   60  06-01-2022  Delivered
31043  31044  405-4724097-1016369  4724097      M   34  06-01-2022  Delivered
31044  31045  408-3572295-5992330  3572295      M   29  06-01-2022  Delivered
31045  31046  405-1423498-9705162  1423498      M   46  06-01-2022  Delivered
31046  31047  408-4694875-8249153  4694875      M   36  06-01-2022  Delivered

       Channel                       SKU       Category Size  Qty currency  \
0        Myntra  JNE1233-BLUE-KR-031-XXL          kurta  XXL    1      INR
1          Ajio           SET414-KR-NP-L            Set    L    1      INR
2        Myntra           SET261-KR-PP-S            Set    S    1      INR
3        Amazon           SET110-KR-PP-M            Set    M    1      INR
4        Myntra         JNE2294-KR-A-XXL          kurta  XXL    1      INR
...         ...                      ...            ...  ...  ...      ...
31042  Flipkart              J0083-KR-XL          kurta   XL  One      INR
31043    Myntra              J0010-LCD-S            Set    S  One      INR
31044    Amazon           SET398-KR-PP-L            Set    L  One      INR
31045    Amazon             JNE3568-KR-M          kurta    M  One      INR
31046  Flipkart            J0341-DR-XXXL  Western Dress  3XL  One      INR

       Amount    ship-city   ship-state  ship-postal-code ship-country    B2B
0         376       MOHALI       PUNJAB            140301           IN  False
1        1449     GURUGRAM      HARYANA            122002           IN  False
2         453      KOLKATA  WEST BENGAL            700029           IN  False
3         729    THANJAVUR   TAMIL NADU            613007           IN  False
4         544     GURUGRAM      HARYANA            122001           IN  False
...       ...          ...          ...               ...          ...    ...
31042     565         PUNE  MAHARASHTRA            412307           IN  False
31043     939    BENGALURU    KARNATAKA            560061           IN  False
31044    1115  PITHORAGARH  UTTARAKHAND            262501           IN  False
31045     399        DHULE  MAHARASHTRA            424006           IN  False
31046     791     WARANGAL    TELANGANA            506001           IN  False

[31047 rows x 19 columns]

In [4]:
#let's check how many row and coulmns in dataset
print("Row and Columns :",vssd.shape)

Row and Columns : (31047, 19)

In [5]:
#Let's chaeck info about dataset
vssd_info = vssd.info()                                                           #Here we see there in no any null values in any columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31047 entries, 0 to 31046
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   index             31047 non-null  int64
 1   Order ID          31047 non-null  object
 2   Cust ID           31047 non-null  int64
 3   Gender            31047 non-null  object
 4   Age               31047 non-null  int64
 5   Date              31047 non-null  object
 6   Status            31047 non-null  object
 7   Channel           31047 non-null  object
 8   SKU               31047 non-null  object
 9   Category          31047 non-null  object
 10  Size              31047 non-null  object
 11  Qty               31047 non-null  object
 12  currency          31047 non-null  object
 13  Amount            31047 non-null  int64
 14  ship-city         31047 non-null  object
 15  ship-state        31047 non-null  object
 16  ship-postal-code  31047 non-null  int64
 17  ship-country      31047 non-null  object
 18  B2B               31047 non-null  bool
dtypes: bool(1), int64(5), object(13)
memory usage: 4.3+ MB

In [6]:
#let we count to confirm there is no null values
vssd_nv = vssd.isnull().sum()
print(vssd_nv)
#Here we see there is no need to fill any values because there is no null values in our dataset

index               0
Order ID            0
Cust ID             0
Gender              0
Age                 0
Date                0
Status              0
Channel             0
SKU                 0
Category            0
Size                0
Qty                 0
currency            0
Amount              0
ship-city           0
ship-state          0
ship-postal-code    0
ship-country        0
B2B                 0
dtype: int64

In [7]:
#Let check or Count duplicate values in dataset
vssd_duplicates = vssd.duplicated().sum()
print("Duplicate Values in Dataset : ",vssd_duplicates)
                                                                                        #Here we see there is no duplicate values in it

Duplicate Values in Dataset :  0

In [8]:
#Let revise our data of top 10 persons and last 10 persons and Last 10 persons
vssd.head(10)

,index,Order ID,Cust ID,Gender,Age,Date,Status,Channel,SKU,Category,Size,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B
0,1,171-1029312-3038738,1029312,Women,44,04-12-2022,Delivered,Myntra,JNE1233-BLUE-KR-031-XXL,kurta,XXL,1,INR,376,MOHALI,PUNJAB,140301,IN,False
1,2,405-2183842-2225946,2183842,Women,29,04-12-2022,Delivered,Ajio,SET414-KR-NP-L,Set,L,1,INR,1449,GURUGRAM,HARYANA,122002,IN,False
2,3,171-1641533-8921966,1641533,Women,67,04-12-2022,Delivered,Myntra,SET261-KR-PP-S,Set,S,1,INR,453,KOLKATA,WEST BENGAL,700029,IN,False
3,4,404-7490807-6300351,7490807,Women,20,04-12-2022,Delivered,Amazon,SET110-KR-PP-M,Set,M,1,INR,729,THANJAVUR,TAMIL NADU,613007,IN,False
4,5,403-9293516-4577154,9293516,Women,62,04-12-2022,Delivered,Myntra,JNE2294-KR-A-XXL,kurta,XXL,1,INR,544,GURUGRAM,HARYANA,122001,IN,False
5,6,407-1298130-0368305,1298130,Men,49,04-12-2022,Delivered,Flipkart,JNE3797-KR-XXL,Western Dress,XXL,One,INR,735,SANGLI MIRAJ KUPWAD,MAHARASHTRA,416436,IN,False
6,7,407-1298130-0368305,1298130,W,23,04-12-2022,Delivered,Meesho,JNE3801-KR-XXL,kurta,XXL,One,INR,735,BENGALURU,KARNATAKA,560029,IN,False
7,8,171-5561216-3398711,5561216,W,70,04-12-2022,Delivered,Others,JNE3405-KR-M,kurta,M,One,INR,435,GURUGRAM,HARYANA,122001,IN,False
8,9,408-2935263-2935550,2935263,W,75,04-12-2022,Delivered,Amazon,JNE3474-KR-E-XL,kurta,XL,One,INR,385,BENGALURU,KARNATAKA,562149,IN,False
9,10,404-2648970-9042715,2648970,W,43,04-12-2022,Delivered,Myntra,JNE3466-KR-L,kurta,L,One,INR,771,VIJAYAWADA,ANDHRA PRADESH,520002,IN,False

In [9]:
vssd.tail(10)

,index,Order ID,Cust ID,Gender,Age,Date,Status,Channel,SKU,Category,Size,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B
31037,31038,405-6870909-7366760,6870909,M,73,06-01-2022,Delivered,Myntra,JNE3798-KR-XL,Western Dress,XL,1,INR,735,KANPUR,UTTAR PRADESH,208001,IN,False
31038,31039,406-3695146-6880344,3695146,W,31,06-01-2022,Delivered,Flipkart,JNE3745-KR-S,kurta,S,1,INR,292,VADODARA,GUJARAT,390020,IN,False
31039,31040,405-7447678-6283558,7447678,M,30,06-01-2022,Delivered,Myntra,JNE3676-TU-S,Top,S,1,INR,385,Hyderabad,TELANGANA,500015,IN,False
31040,31041,405-4837393-8997115,4837393,M,60,06-01-2022,Delivered,Ajio,MEN5027-KR-M,kurta,M,One,INR,495,HYDERABAD,TELANGANA,500084,IN,False
31041,31042,405-4724097-1016369,4724097,W,46,06-01-2022,Delivered,Myntra,J0277-SKD-S,Set,S,One,INR,1333,VADODARA,GUJARAT,390008,IN,False
31042,31043,405-4724097-1016369,4724097,M,60,06-01-2022,Delivered,Flipkart,J0083-KR-XL,kurta,XL,One,INR,565,PUNE,MAHARASHTRA,412307,IN,False
31043,31044,405-4724097-1016369,4724097,M,34,06-01-2022,Delivered,Myntra,J0010-LCD-S,Set,S,One,INR,939,BENGALURU,KARNATAKA,560061,IN,False
31044,31045,408-3572295-5992330,3572295,M,29,06-01-2022,Delivered,Amazon,SET398-KR-PP-L,Set,L,One,INR,1115,PITHORAGARH,UTTARAKHAND,262501,IN,False
31045,31046,405-1423498-9705162,1423498,M,46,06-01-2022,Delivered,Amazon,JNE3568-KR-M,kurta,M,One,INR,399,DHULE,MAHARASHTRA,424006,IN,False
31046,31047,408-4694875-8249153,4694875,M,36,06-01-2022,Delivered,Flipkart,J0341-DR-XXXL,Western Dress,3XL,One,INR,791,WARANGAL,TELANGANA,506001,IN,False

In [10]:
#We see as per our dataset ,in 'Qty' there is rendomly written '1' or 'One' , Lets replace it 'One' = '1' & correct 'Gender' column:
vssd["Qty"] = vssd["Qty"].replace("One","1")
vssd["Gender"] = vssd["Gender"].replace({"W" : "Female",
                                            "M" : "Male",
                                            "Men" : "Male",
                                             "Women": "Female"})
                                                                             #Let's check it replace or not?
print(vssd.head(10))

   index             Order ID  Cust ID  Gender  Age        Date     Status  \
0      1  171-1029312-3038738  1029312  Female   44  04-12-2022  Delivered
1      2  405-2183842-2225946  2183842  Female   29  04-12-2022  Delivered
2      3  171-1641533-8921966  1641533  Female   67  04-12-2022  Delivered
3      4  404-7490807-6300351  7490807  Female   20  04-12-2022  Delivered
4      5  403-9293516-4577154  9293516  Female   62  04-12-2022  Delivered
5      6  407-1298130-0368305  1298130    Male   49  04-12-2022  Delivered
6      7  407-1298130-0368305  1298130  Female   23  04-12-2022  Delivered
7      8  171-5561216-3398711  5561216  Female   70  04-12-2022  Delivered
8      9  408-2935263-2935550  2935263  Female   75  04-12-2022  Delivered
9     10  404-2648970-9042715  2648970  Female   43  04-12-2022  Delivered

   Channel                       SKU       Category Size Qty currency  Amount  \
0    Myntra  JNE1233-BLUE-KR-031-XXL          kurta  XXL   1      INR     376
1      Ajio           SET414-KR-NP-L            Set    L   1      INR    1449
2    Myntra           SET261-KR-PP-S            Set    S   1      INR     453
3    Amazon           SET110-KR-PP-M            Set    M   1      INR     729
4    Myntra         JNE2294-KR-A-XXL          kurta  XXL   1      INR     544
5  Flipkart           JNE3797-KR-XXL  Western Dress  XXL   1      INR     735
6    Meesho           JNE3801-KR-XXL          kurta  XXL   1      INR     735
7    Others             JNE3405-KR-M          kurta    M   1      INR     435
8    Amazon          JNE3474-KR-E-XL          kurta   XL   1      INR     385
9    Myntra             JNE3466-KR-L          kurta    L   1      INR     771

             ship-city      ship-state  ship-postal-code ship-country    B2B
0               MOHALI          PUNJAB            140301           IN  False
1             GURUGRAM         HARYANA            122002           IN  False
2              KOLKATA     WEST BENGAL            700029           IN  False
3            THANJAVUR      TAMIL NADU            613007           IN  False
4             GURUGRAM         HARYANA            122001           IN  False
5  SANGLI MIRAJ KUPWAD     MAHARASHTRA            416436           IN  False
6            BENGALURU       KARNATAKA            560029           IN  False
7             GURUGRAM         HARYANA            122001           IN  False
8            BENGALURU       KARNATAKA            562149           IN  False
9           VIJAYAWADA  ANDHRA PRADESH            520002           IN  False

In [11]:
#Let's check out data's profit or loss (mean,std,min,max...etc)
vssd.describe()

             index       Cust ID           Age        Amount  ship-postal-code
count  31047.00000  3.104700e+04  31047.000000  31047.000000      31047.000000
mean   15524.00000  4.936824e+06     39.496570    682.074822     460474.587206
std     8962.64124  2.900678e+06     15.117233    268.582173     198116.733009
min        1.00000  8.950000e+02     18.000000    229.000000     110001.000000
25%     7762.50000  2.416471e+06     28.000000    486.000000     313001.000000
50%    15524.00000  4.909885e+06     37.000000    646.000000     500028.000000
75%    23285.50000  7.454182e+06     47.000000    794.000000     600040.000000
max    31047.00000  9.999233e+06     78.000000   3036.000000     855117.000000

In [12]:
vssd.rename(columns = {"Order ID" : "Order_Id",
              "Cust Id":"Cust_Id"},inplace = True)
vssd.head()

,index,Order_Id,Cust ID,Gender,Age,Date,Status,Channel,SKU,Category,Size,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B
0,1,171-1029312-3038738,1029312,Female,44,04-12-2022,Delivered,Myntra,JNE1233-BLUE-KR-031-XXL,kurta,XXL,1,INR,376,MOHALI,PUNJAB,140301,IN,False
1,2,405-2183842-2225946,2183842,Female,29,04-12-2022,Delivered,Ajio,SET414-KR-NP-L,Set,L,1,INR,1449,GURUGRAM,HARYANA,122002,IN,False
2,3,171-1641533-8921966,1641533,Female,67,04-12-2022,Delivered,Myntra,SET261-KR-PP-S,Set,S,1,INR,453,KOLKATA,WEST BENGAL,700029,IN,False
3,4,404-7490807-6300351,7490807,Female,20,04-12-2022,Delivered,Amazon,SET110-KR-PP-M,Set,M,1,INR,729,THANJAVUR,TAMIL NADU,613007,IN,False
4,5,403-9293516-4577154,9293516,Female,62,04-12-2022,Delivered,Myntra,JNE2294-KR-A-XXL,kurta,XXL,1,INR,544,GURUGRAM,HARYANA,122001,IN,False

In [13]:
# Here we observe we remove currency column because the currency in INR common in all orders
vssd.drop(["currency"],axis = 1)

,index,Order_Id,Cust ID,Gender,Age,Date,Status,Channel,SKU,Category,Size,Qty,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B
0,1,171-1029312-3038738,1029312,Female,44,04-12-2022,Delivered,Myntra,JNE1233-BLUE-KR-031-XXL,kurta,XXL,1,376,MOHALI,PUNJAB,140301,IN,False
1,2,405-2183842-2225946,2183842,Female,29,04-12-2022,Delivered,Ajio,SET414-KR-NP-L,Set,L,1,1449,GURUGRAM,HARYANA,122002,IN,False
2,3,171-1641533-8921966,1641533,Female,67,04-12-2022,Delivered,Myntra,SET261-KR-PP-S,Set,S,1,453,KOLKATA,WEST BENGAL,700029,IN,False
3,4,404-7490807-6300351,7490807,Female,20,04-12-2022,Delivered,Amazon,SET110-KR-PP-M,Set,M,1,729,THANJAVUR,TAMIL NADU,613007,IN,False
4,5,403-9293516-4577154,9293516,Female,62,04-12-2022,Delivered,Myntra,JNE2294-KR-A-XXL,kurta,XXL,1,544,GURUGRAM,HARYANA,122001,IN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31042,31043,405-4724097-1016369,4724097,Male,60,06-01-2022,Delivered,Flipkart,J0083-KR-XL,kurta,XL,1,565,PUNE,MAHARASHTRA,412307,IN,False
31043,31044,405-4724097-1016369,4724097,Male,34,06-01-2022,Delivered,Myntra,J0010-LCD-S,Set,S,1,939,BENGALURU,KARNATAKA,560061,IN,False
31044,31045,408-3572295-5992330,3572295,Male,29,06-01-2022,Delivered,Amazon,SET398-KR-PP-L,Set,L,1,1115,PITHORAGARH,UTTARAKHAND,262501,IN,False
31045,31046,405-1423498-9705162,1423498,Male,46,06-01-2022,Delivered,Amazon,JNE3568-KR-M,kurta,M,1,399,DHULE,MAHARASHTRA,424006,IN,False
31046,31047,408-4694875-8249153,4694875,Male,36,06-01-2022,Delivered,Flipkart,J0341-DR-XXXL,Western Dress,3XL,1,791,WARANGAL,TELANGANA,506001,IN,False

In [14]:
#Saving our CLeanned Data
vssd.head(10000).to_csv("Project1.csv",index=False)
print("File Saving Process Completed!!!")

File Saving Process Completed!!!

In [15]:
print("="*60)
print("Summery of My Project:")
print("="*60)

print("1. Importing libraries.")
print("-"*150)
print("2. Load our uncleanned dataset")
print("-"*150)
print("3. Review our data such as: what we have to do to clean our data (like null values, duplicates values) ")
print("-"*150)
print("4. Cheack columns is there any kind of mistake")
print("-"*150)
print("5. In last we save our cleanned data ")
print("-"*150)

============================================================
Summery of My Project:
============================================================
1. Importing libraries.
------------------------------------------------------------------------------------------------------------------------------------------------------
2. Load our uncleanned dataset
------------------------------------------------------------------------------------------------------------------------------------------------------
3. Review our data such as: what we have to do to clean our data (like null values, duplicates values)
------------------------------------------------------------------------------------------------------------------------------------------------------
4. Cheack columns is there any kind of mistake
------------------------------------------------------------------------------------------------------------------------------------------------------
5. In last we save our cleanned data
------------------------------------------------------------------------------------------------------------------------------------------------------